import { useMemo, useState } from 'react';
import { useWatchlistScanner } from '../hooks/useWatchlistScanner';
import { buildBatchAIPrompt } from '../lib/formatBatchAIPrompt';
import { buildAIPrompt } from '../lib/formatAIPrompt';
import { DEFAULT_SYMBOLS, WATCHLIST_STORAGE_KEY, normalizeSymbol } from '../lib/marketData';

function loadWatchlist() {
  try { const stored = JSON.parse(window.localStorage.getItem(WATCHLIST_STORAGE_KEY) ?? '[]'); return [...new Set((stored.length ? stored : DEFAULT_SYMBOLS).map((item) => normalizeSymbol(String(item))).filter(Boolean))]; }
  catch { return DEFAULT_SYMBOLS; }
}
function fmt(value, digits = 2) { return Number.isFinite(Number(value)) ? Number(value).toLocaleString('en-US', { maximumFractionDigits: digits }) : '--'; }
function trendTone(trend) { return trend === 'BULLISH' ? 'text-emerald-400' : trend === 'BEARISH' ? 'text-red-400' : 'text-zinc-400'; }
function scoreTone(score) { return score >= 85 ? 'text-emerald-400' : score >= 75 ? 'text-yellow-300' : score >= 65 ? 'text-orange-300' : 'text-zinc-500'; }

export default function ScannerDashboard() {
  const [symbols, setSymbols] = useState(loadWatchlist);
  const [mode, setMode] = useState('all');
  const [input, setInput] = useState('');
  const [copied, setCopied] = useState(false);
  const [copiedSymbol, setCopiedSymbol] = useState('');
  const [refreshToken, setRefreshToken] = useState(0);
  const [selected, setSelected] = useState(null);
  const { scans } = useWatchlistScanner(symbols, 'conservative', refreshToken);

  const ranked = useMemo(() => {
    const key = mode === '4h' ? 'score4h' : mode === '15m' ? 'score15m' : 'score';
    return [...scans].sort((a, b) => (b?.ranking?.[key] ?? 0) - (a?.ranking?.[key] ?? 0)).map((scan, index) => ({ ...scan, displayRank: index + 1, displayScore: scan.ranking?.[key] ?? 0, displayDirection: mode === '4h' ? scan.htf?.trend : mode === '15m' ? scan.setup?.trend : scan.ranking?.direction }));
  }, [mode, scans]);
  const selectedScan = selected ? scans.find((scan) => scan.symbol === selected) : null;
  const selectedOi = selectedScan?.derivatives?.openInterest ?? {};
  const selectedTaker = selectedScan?.derivatives?.taker ?? {};
  const lastDataAt = useMemo(() => { const times = scans.map((scan) => scan.updatedAt).filter(Boolean); return times.length ? new Date(Math.max(...times)).toLocaleTimeString() : '--'; }, [scans]);

  async function copyAll() { await navigator.clipboard.writeText(buildBatchAIPrompt(ranked, { mode, timestamp: new Date().toISOString() })); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  async function copyOne(scan) { await navigator.clipboard.writeText(buildAIPrompt(scan, { mode })); setCopiedSymbol(scan.symbol); window.setTimeout(() => setCopiedSymbol(''), 1600); }
  function addSymbol() { const symbol = normalizeSymbol(input); if (!symbol || symbols.includes(symbol)) return; const next = [...symbols, symbol]; setSymbols(next); window.localStorage.setItem(WATCHLIST_STORAGE_KEY, JSON.stringify(next)); setInput(''); }
  function removeSymbol(symbol) { const next = symbols.filter((item) => item !== symbol); const saved = next.length ? next : DEFAULT_SYMBOLS; setSymbols(saved); window.localStorage.setItem(WATCHLIST_STORAGE_KEY, JSON.stringify(saved)); if (selected === symbol) setSelected(null); }

  return <main className="min-h-screen bg-[#09090b] px-3 py-4 text-zinc-100 md:px-6 md:py-6"><div className="mx-auto max-w-7xl space-y-4">
    <header className="rounded-2xl border border-zinc-800 bg-zinc-950/90 p-4 shadow-2xl md:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[10px] font-semibold uppercase tracking-[0.22em] text-zinc-500">BINANCE FUTURES</div><h1 className="mt-1 text-2xl font-bold tracking-tight">交易机会排行</h1><p className="mt-1 text-xs text-zinc-500">4H与15M使用独立评分体系。程序评分只负责排序，最终判断交给AI。</p></div><div className="flex flex-wrap gap-2">{[['all','全部'],['4h','4H短线'],['15m','15M超短线']].map(([v,l]) => <button key={v} type="button" onClick={() => setMode(v)} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${mode === v ? 'border-indigo-400 bg-indigo-500 text-white' : 'border-zinc-700 bg-zinc-900 text-zinc-400'}`}>{l}</button>)}<button type="button" onClick={() => setRefreshToken((v) => v + 1)} className="rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs font-semibold text-zinc-300">立即刷新</button><button type="button" onClick={copyAll} className="rounded-lg border border-emerald-700 bg-emerald-950/40 px-3 py-2 text-xs font-semibold text-emerald-300">{copied ? '已复制' : '复制全部AI数据'}</button></div></div></header>
    <section className="flex flex-col gap-3 rounded-2xl border border-zinc-800 bg-zinc-950/80 p-3 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-2 text-xs text-zinc-400"><span className="h-2 w-2 rounded-full bg-emerald-400" />实时行情约10秒更新 · 技术/衍生品约2分钟更新 · 数据 {lastDataAt}</div><div className="flex gap-2"><input value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addSymbol()} placeholder="添加币种，例如 HYPE" className="w-40 rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs outline-none placeholder:text-zinc-600" /><button type="button" onClick={addSymbol} className="rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs font-semibold text-zinc-300">添加</button></div></section>
    <section className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-950/80"><div className="overflow-x-auto"><table className="min-w-[1040px] w-full text-left text-xs"><thead className="border-b border-zinc-800 text-[10px] uppercase tracking-wider text-zinc-600"><tr><th className="px-4 py-3">#</th><th className="px-4 py-3">币种</th><th className="px-4 py-3">{mode === '4h' ? '4H评分' : mode === '15m' ? '15M评分' : '综合评分'}</th><th className="px-4 py-3">方向</th><th className="px-4 py-3">4H评分</th><th className="px-4 py-3">15M评分</th><th className="px-4 py-3">OI Δ1H</th><th className="px-4 py-3">Taker</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">操作</th></tr></thead><tbody>{ranked.map((scan) => { const oi = scan.derivatives?.openInterest ?? {}, taker = scan.derivatives?.taker ?? {}; return <tr key={scan.symbol} className="border-b border-zinc-900 hover:bg-zinc-900/70"><td className="px-4 py-3 font-mono text-zinc-600">{scan.displayRank}</td><td className="px-4 py-3"><button type="button" onClick={() => setSelected(scan.symbol)} className="text-left"><div className="font-bold hover:text-indigo-300">{scan.symbol.replace('USDT','')}</div><div className="font-mono text-[10px] text-zinc-600">${fmt(scan.price,6)}</div></button></td><td className={`px-4 py-3 font-mono text-base font-bold ${scoreTone(scan.displayScore)}`}>{scan.displayScore}</td><td className={`px-4 py-3 font-semibold ${trendTone(scan.displayDirection)}`}>{scan.displayDirection === 'BULLISH' ? '↑ 做多偏向' : scan.displayDirection === 'BEARISH' ? '↓ 做空偏向' : '→ 中性'}</td><td className="px-4 py-3 font-mono text-zinc-300">{fmt(scan.ranking?.score4h,0)}</td><td className="px-4 py-3 font-mono text-zinc-300">{fmt(scan.ranking?.score15m,0)}</td><td className="px-4 py-3 font-mono text-zinc-300">{fmt(oi.change1hPct)}%</td><td className="px-4 py-3 font-mono text-zinc-300">{fmt(taker.buySellRatio)}</td><td className="px-4 py-3">{scan.dataQuality === 'GOOD' ? <span className="text-emerald-400">正常</span> : <span className="text-orange-300">{scan.dataQuality}</span>}</td><td className="px-4 py-3"><button type="button" onClick={() => copyOne(scan)} className="mr-3 text-indigo-300">{copiedSymbol === scan.symbol ? '已复制' : '复制AI'}</button><button type="button" onClick={() => removeSymbol(scan.symbol)} className="text-zinc-600 hover:text-red-400">移除</button></td></tr>; })}</tbody></table></div></section>
    {selectedScan && <section className="rounded-2xl border border-zinc-800 bg-zinc-950/90 p-4"><div className="flex items-center justify-between"><div><div className="text-lg font-bold">{selectedScan.symbol.replace('USDT','')} 详细数据</div><div className="text-xs text-zinc-600">价格 ${fmt(selectedScan.price,6)} · 4H {fmt(selectedScan.ranking?.score4h,0)} · 15M {fmt(selectedScan.ranking?.score15m,0)}</div></div><button type="button" onClick={() => setSelected(null)} className="text-zinc-500">关闭</button></div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-zinc-900 p-3"><div className="text-[10px] text-zinc-600">4H结构</div><div className={trendTone(selectedScan.htf.trend)}>{selectedScan.htf.trend} · {selectedScan.htf.structure}</div><div className="mt-2 text-xs text-zinc-400">评分 {fmt(selectedScan.ranking?.score4h,0)} · EMA20/50/200 {fmt(selectedScan.htf.ema20,4)} / {fmt(selectedScan.htf.ema50,4)} / {fmt(selectedScan.htf.ema200,4)}</div></div><div className="rounded-xl bg-zinc-900 p-3"><div className="text-[10px] text-zinc-600">15M结构</div><div className={trendTone(selectedScan.setup.trend)}>{selectedScan.setup.trend} · {selectedScan.setup.structure}</div><div className="mt-2 text-xs text-zinc-400">评分 {fmt(selectedScan.ranking?.score15m,0)} · BOS {selectedScan.setup.bos?.direction ?? '--'} · Retest {selectedScan.setup.retest?.complete ? '完成' : '--'}</div></div><div className="rounded-xl bg-zinc-900 p-3"><div className="text-[10px] text-zinc-600">衍生品</div><div className="text-xs text-zinc-300">OI Δ1H {fmt(selectedOi.change1hPct)}%</div><div className="text-xs text-zinc-400">OI Δ4H {fmt(selectedOi.change4hPct)}% · L/S {fmt(selectedScan.derivatives?.longShort?.longShortRatio)}</div><div className="text-xs text-zinc-400">Taker {fmt(selectedTaker.buySellRatio)}</div></div><div className="rounded-xl bg-zinc-900 p-3"><div className="text-[10px] text-zinc-600">关键位置</div><div className="text-xs text-zinc-300">4H 支撑 {fmt(selectedScan.htf.support,6)}</div><div className="text-xs text-zinc-300">4H 阻力 {fmt(selectedScan.htf.resistance,6)}</div><div className="text-xs text-zinc-400">15M 成交量 {fmt(selectedScan.setup.volumeRatio,2)}x</div></div></div><button type="button" onClick={() => copyOne(selectedScan)} className="mt-3 rounded-lg border border-emerald-700 bg-emerald-950/30 px-3 py-2 text-xs font-semibold text-emerald-300">复制此币完整AI数据</button></section>}
    <section className="rounded-2xl border border-zinc-800 bg-zinc-950/80 p-4 text-xs text-zinc-500"><div className="font-semibold text-zinc-300">评分体系</div><div className="mt-2 grid gap-2 md:grid-cols-3"><div>4H：趋势 20 · 结构 15 · OI 8 · Funding 5 · BTC 5</div><div>15M：结构 20 · 动量 10 · 成交量 10 · OI 8</div><div>15M额外：Taker/CVD 7 · Funding 2 · 4H对齐 5</div></div><div className="mt-2">全部 = 4H 45% + 15M 55%。评分仅用于排序，AI必须重新判断，数据异常则不得强行交易。</div></section>
  </div></main>;
}
